### ISSUE TITLE
Crash when opening app on Android

### ISSUE THREAD

**Issue by dccarmo** [globocom/react-native-ua#36]
Here's the stack trace:

```
12-15 18:56:11.272  4035  4073 E AndroidRuntime: FATAL EXCEPTION: LocationService
12-15 18:56:11.272  4035  4073 E AndroidRuntime: Process: com.foo.bar, PID: 4035
12-15 18:56:11.272  4035  4073 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "com.google.android.gms.common.api.Api$zze com.google.android.gms.common.api.Api$zza.zza(android.content.Context, android.os.Looper, com.google.android.gms.common.internal.zzf, java.lang.Object, com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks, com.google.android.gms.common.api.GoogleApiClient$OnConnectionFailedListener)"
12-15 18:56:11.272  4035  4073 E AndroidRuntime:    at com.google.android.gms.common.api.GoogleApiClient$Builder.zza(Unknown Source)
12-15 18:56:11.272  4035  4073 E AndroidRuntime:    at com.google.android.gms.common.api.GoogleApiClient$Builder.zzarg(Unknown Source)
12-15 18:56:11.272  4035  4073 E AndroidRuntime:    at com.google.android.gms.common.api.GoogleApiClient$Builder.build(Unknown Source)
12-15 18:56:11.272  4035  4073 E AndroidRuntime:    at com.urbanairship.location.FusedLocationAdapter.connect(FusedLocationAdapter.java:108)
12-15 18:56:11.272  4035  4073 E AndroidRuntime:    at com.urbanairship.location.UALocationProvider.cancelRequests(UALocationProvider.java:63)
12-15 18:56:11.272  4035  4073 E AndroidRuntime:    at com.urbanairship.location.LocationService.onCheckLocationUpdates(LocationService.java:424)
12-15 18:56:11.272  4035  4073 E AndroidRuntime:    at com.urbanairship.location.LocationService.onHandleIntent(LocationService.java:195)
12-15 18:56:11.272  4035  4073 E AndroidRuntime:    at com.urbanairship.location.LocationService.access$600(LocationService.java:38)
12-15 18:56:11.272  4035  4073 E AndroidRuntime:    at com.urbanairship.location.LocationService$IncomingHandler.handleMessage(LocationService.java:556)
12-15 18:56:11.272  4035  4073 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:102)
12-15 18:56:11.272  4035  4073 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:148)
12-15 18:56:11.272  4035  4073 E AndroidRuntime:    at android.os.HandlerThread.run(HandlerThread.java:61)
```

The thing is, this issue only occurs on Android 6. If I run the exact same project on 7, it works great.

I'm not sure if it's related to this plugin or the native SDK, but I thought I should post here first.

Looking around the internet this kind of error seems to be related to incompatibilities with the App's dependencies, but I can't figure out how to fix it.

Any ideas?

**Comment by rlepinski** [comment]
Latest SDK compiles against Google Play Services 9.8 but it looks like its requesting 9.4 location module - https://github.com/globocom/react-native-ua/blob/master/android/build.gradle#L43. Then you will have a mix of 9.8 and 9.4. I recommend updating it to:
```
    compile 'com.google.android.gms:play-services-gcm:[9.8.0,10['
    compile 'com.google.android.gms:play-services-location:[9.8.0,10['
```

**Comment by dccarmo** [comment]
You meant update `react-native-ua` `build.gradle`, right? 'Cause I did it on my local version, and I'm still getting the same error.

**Comment by rlepinski** [comment]
@dccarmo do you have any other build.gradle file dependencies that you can post?

**Comment by dccarmo** [comment]
Yep, this is my app dependencies:

```
dependencies {
    compile project(':react-native-maps')
    compile 'io.intercom.android:intercom-sdk:3.+'
    compile project(':react-native-intercom')
    compile project(':realm')
    compile project(':react-native-svg')
    compile project(':react-native-linear-gradient')
    compile project(':react-native-ua')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile "com.google.android.gms:play-services-base:+"
    compile 'com.google.android.gms:play-services-maps:+'
}
```

**Comment by rlepinski** [comment]
Ok, can you try adding to the above list:
```
compile 'com.google.android.gms:play-services-gcm:+`
compile 'com.google.android.gms:play-services-location:+'
```

**Comment by dccarmo** [comment]
Super! That fixed it. 

@rlepinski So are these dependencies mandatory? Maybe we should list them on the docs. I can create a PR for that (and for the plugin `build.gradle` update.)

**Comment by rlepinski** [comment]
@dccarmo The react-native build.gradle file is pulling them in, not sure why `[9.8.0,10[` didn't resolve the right version. I might have the syntax off a bit. I think maybe its `[9.8.0,)` Basically trying to specify any version  9.8 or newer.

http://ant.apache.org/ivy/history/2.1.0/settings/version-matchers.html
